### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by PublicSeaLion** [MythicManiac/League-of-Legends#1]
No matter what I do I get this error. http://puu.sh/fbjYj/45df2e106c.png

**Comment by MythicManiac** [comment]
Do you mind posting the error that was logged to the log as well?

**Comment by PublicSeaLion** [comment]
Where do I find the logs?

**Comment by MythicManiac** [comment]
The logs are located in `League of Legends\Mythic\Log.txt`, that first folder being your League of Legends installation folder.

**Comment by PublicSeaLion** [comment]
I don't have this folder.

**Comment by MythicManiac** [comment]
My guess would be that you're looking from the wrong place, since the application would crash before the point you showed in the image if the folder didn't exist. Try right clicking the League of Legends launcher icon, and selecting "Open file location". This should take you to where the `Mythic\` folder is located at.

You can add me at Skype if you'd like, my username is `mythicpotato`. I can probably help resolve this faster there.

**Comment by PublicSeaLion** [comment]
http://puu.sh/fdGij/042b794743.png is what it looks like.

**Comment by MythicManiac** [comment]
By the looks of it, I'd guess the registry entry of your League of Legends is pointing somewhere else than the actual installation location. This means you'll either have to modify your registry to point towards the real location, re-install your client, or wait until I think of a workaround. Have you ever moved your League installation or something similar? If you have, it would explain the problem, if not, there might be something else wrong. I'll get back to you later today with a fix.

**Comment by MythicManiac** [comment]
Alright, [Version 1.0.2](https://github.com/MythicManiac/League-of-Legends/releases/download/v1.0.2/League.Scrambler.v1.0.2.zip) should fix it for you.

If that doesn't work straight away, edit the "leaguepath.txt" and make the path match the proper location. If you do edit it, make sure there's only one line of text and a backslash at the end.

Please let me know if this works.

**Comment by PublicSeaLion** [comment]
This worked, thank you.

**Comment by MythicManiac** [comment]
This problem has now been properly fixed in the newest version.
